### ISSUE TITLE
Get the URI on the model API response

### ISSUE THREAD

**Issue by kevinblanco** [lachoseparis/lachose-strapi-plugins#1]
This plugin works great, but, I'd like the URI value to be part of the standard API response of my model, my front-end developers get a collection of speakers (`/api/speakers`) and i'd like that value to be there so when someone clicks on the speaker we can get the proxy from your API.

**Comment by Norbz** [comment]
Hi @kevinblanco 

Thanks for your message :)

This use case is indeed useful, but as the URI aren't saved in the model but are saved as a polymorphic relationship, adding the URI could hurt the performance for large collection. This is why we only added it in a single model metadata (`/api/spearkers/<id>`) and didn't added them for collection, at least for now.

In the mean time, it is easy to implement on your project side, so right now I could recommend that you add a custom controller for your speaker collection and query the corresponding URIs :

```
const uris = await strapi.entityService.findMany('plugin::custom-links.custom-link', {
          filters: { kind: 'api::speaker.speaker', contentId: {$in:[<...your ids...> ]}},
});
```

Then match the URIs to your speakers based on contentId.

Let me know how that works for you :)
