### ISSUE TITLE
Strapi  log me out when i try to access to the content builder section

### ISSUE THREAD

**Issue by bmartinezg** [lachoseparis/lachose-strapi-plugins#6]
After configure the plugin, i try to access to the content build section but i get log out always.

here is muy package.json
````json

 "scripts": {
    "dev": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi"
  },
  "devDependencies": {},
  "dependencies": {
    "@strapi/plugin-i18n": "4.10.5",
    "@strapi/plugin-seo": "^1.8.0",
    "@strapi/plugin-users-permissions": "4.10.5",
    "@strapi/strapi": "4.10.5",
    "better-sqlite3": "8.0.1",
    "strapi-plugin-custom-links": "^0.2.1"
  },

````

**Comment by Norbz** [comment]
Hi

Sorry for that much delay.

Problem is occuring when migrating strapi from 4.8.2 to 4.9.0. I've managed to reproduce the issue but to be honest I see no change in plugin dev API that would justify the behavior. I'm getting a 401 on the /content-type route wich is, I suspect, is the reason we are getting logged out.

Still looking into this, if you have any lead please share :)

**Comment by Norbz** [comment]
Hi again

Version 0.3.0 should be fixing it.
Let me know if that works for you and reopen the issue if you still have troubles.
